### ISSUE TITLE
exe file in package?

### ISSUE THREAD

**Issue by MilosRasic** [LinusU/node-loudness#16]
This seems a bit extreme. The readme says only Mac and Linux are supported, so why not keep the Windows experiment on a branch? 

There's also windows-specific packages for the same problem, such as win-audio and node-audio-windows, but both are limited to windows in package.json. Not sure if this is enforced for transient dependencies. Would prevent development on non-windows platforms if it is. Maybe add as peer dep?

**Comment by LinusU** [comment]
Windows is not experimental, it's fully supported. I agree that it's not optimal to ship binaries, but at least the file is only 11KiB...

If you have another approach that would work, I would love to see it!
