### ISSUE TITLE
Windows Support.

### ISSUE THREAD

**Issue by octalmage** [LinusU/node-loudness#2]
Hey! 

Thanks for the library, I'm using it for my project [Lull](https://github.com/octalmage/lull).

How would you feel about adding Windows support using [NirCmd](http://www.nirsoft.net/utils/nircmd.html)? This seems like the best way to modify the volume from the command line on Windows. It's a very small binary and it would be easy to distribute. 

I'll submit a PR if you're on-board, but I totally understand if you don't want to do it this way.

**Comment by LinusU** [comment]
Hey, I would absolutely want to support windows. But I'm not sure that NirCmd is the way to go. It doesn't support reading values, only writing.

What do you think about a native module? It should be fairly easy to write one based on this gist: https://gist.github.com/rdp/8363580

**Comment by octalmage** [comment]
Ah I didn't realize you couldn't get the volume with nircmd, that's an issue. 

A native module would definitely be the best method, and I have experience here. I'll look into it when I have time.

**Comment by LinusU** [comment]
I don't know if it's easy to get it to conditionally compile only on Windows thought... As I see it there are three options.

1. Native addon for windows and skip compiling on OS X/Linux
2. Native addon for all platforms
3. Bundle small binary for Windows

I kind of like number 2, but the benefit of number 3 is that it doesn't require having a compiler installed on Windows; which I don't think most people have.

If we do number 3, we could let the source for the binary (should just be one C file?) live in this repository.

**Comment by octalmage** [comment]
From my experience with RobotJS compiling on Windows is a nightmare. Users need Visual Studio 2013 and Python 2.7. You could distribute binaries using node-pre-gyp, but then you have to manage the builds and that's a ton of work. 

Anyway, it would probably be better to do option 3 and avoid the native stuff. 

Should I test the code from the gist?

**Comment by LinusU** [comment]
That would be awesome! I don't have access to a Windows machine so I would really appreciate the help on this :+1:

I think we should be able to base it on that code and then add support for getting and setting `mute`.

**Comment by octalmage** [comment]
Awesome! I'm glad to help. I'll take a look later today and let you know what I find!

**Comment by RIAEvangelist** [comment]
This will be an awesome addition!

**Comment by octalmage** [comment]
Agreed! I'm off starting tomorrow so I plan on knocking this out this week. I'll post updates here.

**Comment by RIAEvangelist** [comment]
sweet :+1:

**Comment by RIAEvangelist** [comment]
![your weekend](https://lygsbtd.files.wordpress.com/2015/05/writing-gif.gif?w=585&h=462)

**Comment by schmic** [comment]
Any updates on this except "not done yet"? :)

**Comment by octalmage** [comment]
Not done yet, sorry. I honestly forgot about this, and I'm very busy at the moment. If someone else wants to take this, please do. If not I'll see what I can do.

**Comment by maboiteaspam** [comment]
hi,

same interest here. 

Have gathered a list of links to make that possible with cross platform support,
https://github.com/maboiteaspam/working-with-volume-control

happy coding !~

**Comment by LinusU** [comment]
Windows support is present in the latest version 👍
